# SPDX-License-Identifier: Apache-2.0
"""Internal DP -> CP control channel: registration and heartbeat.

Production transport is a Unix domain socket inside the supervisor's 0700
workdir; the directory permission is the enforced access boundary (the
socket's own mode is whatever the server stack creates). A localhost TCP
fallback exists for platforms without UDS (tests only, never production); it
is guarded by a per-run random token generated by the supervisor and passed
via SGLANG_OMNI_ROUTER_INTERNAL_TOKEN, so arbitrary local processes cannot
call /internal/* either way.

Heartbeats carry last_applied_seq (the newest worker-snapshot seq the DP has
applied); the weight-update ACK barrier and the CP watchdog read it.
"""

from __future__ import annotations

import hmac
import time

from fastapi import Depends, FastAPI, HTTPException, Request
from pydantic import BaseModel, Field

INTERNAL_TOKEN_ENV = "SGLANG_OMNI_ROUTER_INTERNAL_TOKEN"
INTERNAL_TOKEN_HEADER = "x-sglang-omni-internal-token"

# Note (Jiaxin Deng): control traffic (register, heartbeat, snapshot ACK,
# counters, failure reports) gets its own pool and a timeout well inside the
# liveness and ACK windows. Sharing the forwarding pool would let public admin
# calls parked behind the CP's update lock starve the beats that keep this DP
# counted as live, degrading it and aborting an otherwise safe update.
# Note (Jiaxin Deng): kept at the pre-split size. Failure reports burst on the
# same pool as the beat, and a worker outage is exactly when a weight update
# must still be able to acknowledge the barrier.
CONTROL_CHANNEL_CONNECTIONS = 8
CONTROL_CHANNEL_TIMEOUT_SECS = 5.0
FORWARD_CHANNEL_CONNECTIONS = 8


class DataPlaneHello(BaseModel):
    dp_index: int = Field(ge=0)
    generation: int = Field(ge=1)
    pid: int = Field(ge=1)


class DataPlaneHeartbeat(BaseModel):
    dp_index: int = Field(ge=0)
    generation: int = Field(ge=1)
    pid: int = Field(ge=1)
    last_applied_seq: int = Field(default=0, ge=0)
    # Note (Jiaxin Deng): seqs are only ordered within one cp_epoch; a bare
    # integer from an old epoch must never acknowledge a new epoch's snapshot.
    last_applied_epoch: str = ""
    # Note (Jiaxin Deng): self-reported; false while the DP sheds as
    # snapshot_stale.
    serving: bool = True


class DataPlaneRecord(BaseModel):
    dp_index: int
    generation: int
    pid: int
    last_applied_seq: int = 0
    last_applied_epoch: str = ""
    serving: bool = True
    last_seen_at: float


class InternalChannelState:
    """CP-side view of live data planes, keyed by dp_index.

    Generation fencing: a register with a newer generation replaces the
    record; register or heartbeat with an older generation than the current
    record is rejected (the caller has been fenced out by the supervisor).
    """

    def __init__(self) -> None:
        self.data_planes: dict[int, DataPlaneRecord] = {}

    def register(self, hello: DataPlaneHello) -> DataPlaneRecord:
        current = self.data_planes.get(hello.dp_index)
        if current is not None:
            if hello.generation < current.generation:
                raise StaleGenerationError(hello.generation, current.generation)
            if hello.generation == current.generation and hello.pid != current.pid:
                # Note (Jiaxin Deng): generations are never reused, so an
                # equal-generation register from a different pid is a fenced
                # or impostor process, not a re-register.
                raise StaleGenerationError(hello.generation, current.generation)
        preserved_seq = 0
        preserved_epoch = ""
        preserved_serving = True
        if (
            current is not None
            and hello.generation == current.generation
            and hello.pid == current.pid
        ):
            # Note (Jiaxin Deng): idempotent re-register keeps seq WITH its
            # epoch (a seq under a blank epoch cannot satisfy the ACK barrier)
            # and the serving flag (a shedding DP is not ready until it says so).
            preserved_seq = current.last_applied_seq
            preserved_epoch = current.last_applied_epoch
            preserved_serving = current.serving
        record = DataPlaneRecord(
            dp_index=hello.dp_index,
            generation=hello.generation,
            pid=hello.pid,
            last_applied_seq=preserved_seq,
            last_applied_epoch=preserved_epoch,
            serving=preserved_serving,
            last_seen_at=time.time(),
        )
        self.data_planes[hello.dp_index] = record
        return record

    def heartbeat(self, beat: DataPlaneHeartbeat) -> DataPlaneRecord:
        current = self.data_planes.get(beat.dp_index)
        if current is None or beat.generation > current.generation:
            # Note (Jiaxin Deng): not registered with this CP (it may have
            # restarted); tell the DP to register, do not fence it.
            raise UnknownDataPlaneError(beat.dp_index)
        if beat.generation < current.generation or beat.pid != current.pid:
            raise StaleGenerationError(beat.generation, current.generation)
        if beat.last_applied_epoch == current.last_applied_epoch:
            # Note (Jiaxin Deng): max() so a delayed or replayed heartbeat
            # cannot regress the ACK.
            applied_seq = max(current.last_applied_seq, beat.last_applied_seq)
        else:
            # Note (Jiaxin Deng): new epoch, the seq scale restarted; take it
            # as reported.
            applied_seq = beat.last_applied_seq
        record = DataPlaneRecord(
            dp_index=beat.dp_index,
            generation=beat.generation,
            pid=beat.pid,
            last_applied_seq=applied_seq,
            last_applied_epoch=beat.last_applied_epoch,
            serving=beat.serving,
            last_seen_at=time.time(),
        )
        self.data_planes[beat.dp_index] = record
        return record

    def drop(self, dp_index: int) -> None:
        self.data_planes.pop(dp_index, None)


class StaleGenerationError(Exception):
    def __init__(self, got: int, current: int | None) -> None:
        super().__init__(f"stale generation {got}, current is {current}")
        self.got = got
        self.current = current


class UnknownDataPlaneError(Exception):
    """No record for this dp_index: the caller must (re-)register."""

    def __init__(self, dp_index: int) -> None:
        super().__init__(f"data plane {dp_index} is not registered")
        self.dp_index = dp_index


def make_internal_token_dependency(token: str | None):
    async def _check(request: Request) -> None:
        if token is None:
            return
        provided = request.headers.get(INTERNAL_TOKEN_HEADER, "")
        if not hmac.compare_digest(provided, token):
            raise HTTPException(status_code=403, detail="invalid internal token")

    return _check


def register_internal_routes(
    app: FastAPI, state: InternalChannelState, *, token: str | None
) -> None:
    auth = Depends(make_internal_token_dependency(token))

    @app.post("/internal/register", dependencies=[auth])
    async def _register(hello: DataPlaneHello) -> dict:
        try:
            record = state.register(hello)
        except StaleGenerationError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc
        return {"status": "registered", "dp_index": record.dp_index}

    @app.post("/internal/heartbeat", dependencies=[auth])
    async def _heartbeat(beat: DataPlaneHeartbeat) -> dict:
        try:
            record = state.heartbeat(beat)
        except UnknownDataPlaneError as exc:
            # Note (Jiaxin Deng): 428 = this CP has no record (it may have
            # restarted); the DP should re-register.
            raise HTTPException(status_code=428, detail=str(exc)) from exc
        except StaleGenerationError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc
        return {"status": "ok", "dp_index": record.dp_index}

    @app.get("/internal/data_planes", dependencies=[auth])
    async def _data_planes() -> dict:
        return {
            "data_planes": [
                record.model_dump() for _, record in sorted(state.data_planes.items())
            ]
        }


def create_internal_app(
    state: InternalChannelState | None = None, *, token: str | None = None
) -> FastAPI:
    app = FastAPI()
    app.state.internal_channel = state if state is not None else InternalChannelState()
    register_internal_routes(app, app.state.internal_channel, token=token)
    return app
